/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedVideosRouteImport } from './routes/_authenticated.videos'
import { Route as AuthenticatedScenariosRouteImport } from './routes/_authenticated.scenarios'
import { Route as AuthenticatedPlaybooksRouteImport } from './routes/_authenticated.playbooks'
import { Route as AuthenticatedOrgLibraryRouteImport } from './routes/_authenticated.org-library'
import { Route as AuthenticatedLearnRouteImport } from './routes/_authenticated.learn'
import { Route as AuthenticatedChecklistsRouteImport } from './routes/_authenticated.checklists'
import { Route as AuthenticatedAskRouteImport } from './routes/_authenticated.ask'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated.account'
import { Route as AuthenticatedScenariosIdRouteImport } from './routes/_authenticated.scenarios_.$id'
import { Route as AuthenticatedPlaybooksIdRouteImport } from './routes/_authenticated.playbooks_.$id'
import { Route as AuthenticatedLessonsIdRouteImport } from './routes/_authenticated.lessons_.$id'
import { Route as AuthenticatedAdminVisualReviewRouteImport } from './routes/_authenticated.admin_.visual-review'
import { Route as AuthenticatedAdminVisualNeedsRouteImport } from './routes/_authenticated.admin_.visual-needs'
import { Route as AuthenticatedAdminVisualModeRouteImport } from './routes/_authenticated.admin_.visual-mode'
import { Route as AuthenticatedAdminVisualMapRouteImport } from './routes/_authenticated.admin_.visual-map'
import { Route as AuthenticatedAdminVideoMapRouteImport } from './routes/_authenticated.admin_.video-map'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated.admin_.users'
import { Route as AuthenticatedAdminTaxonomyRouteImport } from './routes/_authenticated.admin_.taxonomy'
import { Route as AuthenticatedAdminSourcesRouteImport } from './routes/_authenticated.admin_.sources'
import { Route as AuthenticatedAdminSourcePacksRouteImport } from './routes/_authenticated.admin_.source-packs'
import { Route as AuthenticatedAdminScreenshotRightsRouteImport } from './routes/_authenticated.admin_.screenshot-rights'
import { Route as AuthenticatedAdminQuestionsRouteImport } from './routes/_authenticated.admin_.questions'
import { Route as AuthenticatedAdminOrgLibraryRouteImport } from './routes/_authenticated.admin_.org-library'
import { Route as AuthenticatedAdminFoundingAccessRouteImport } from './routes/_authenticated.admin_.founding-access'
import { Route as AuthenticatedAdminFeedbackRouteImport } from './routes/_authenticated.admin_.feedback'
import { Route as AuthenticatedAdminFactoryRouteImport } from './routes/_authenticated.admin_.factory'
import { Route as AuthenticatedAdminCoverageRouteImport } from './routes/_authenticated.admin_.coverage'
import { Route as AuthenticatedAdminConversionsRouteImport } from './routes/_authenticated.admin_.conversions'
import { Route as AuthenticatedAdminSourcesIdRouteImport } from './routes/_authenticated.admin_.sources_.$id'
import { Route as AuthenticatedAdminSourcePacksIdRouteImport } from './routes/_authenticated.admin_.source-packs_.$id'
import { Route as AuthenticatedAdminQuestionsIdRouteImport } from './routes/_authenticated.admin_.questions_.$id'
import { Route as AuthenticatedAdminConversionsIdRouteImport } from './routes/_authenticated.admin_.conversions_.$id'

const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => CheckoutRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVideosRoute = AuthenticatedVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScenariosRoute = AuthenticatedScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlaybooksRoute = AuthenticatedPlaybooksRouteImport.update({
  id: '/playbooks',
  path: '/playbooks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrgLibraryRoute = AuthenticatedOrgLibraryRouteImport.update({
  id: '/org-library',
  path: '/org-library',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLearnRoute = AuthenticatedLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChecklistsRoute = AuthenticatedChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAskRoute = AuthenticatedAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScenariosIdRoute =
  AuthenticatedScenariosIdRouteImport.update({
    id: '/scenarios_/$id',
    path: '/scenarios/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlaybooksIdRoute =
  AuthenticatedPlaybooksIdRouteImport.update({
    id: '/playbooks_/$id',
    path: '/playbooks/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLessonsIdRoute = AuthenticatedLessonsIdRouteImport.update({
  id: '/lessons_/$id',
  path: '/lessons/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminVisualReviewRoute =
  AuthenticatedAdminVisualReviewRouteImport.update({
    id: '/admin_/visual-review',
    path: '/admin/visual-review',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminVisualNeedsRoute =
  AuthenticatedAdminVisualNeedsRouteImport.update({
    id: '/admin_/visual-needs',
    path: '/admin/visual-needs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminVisualModeRoute =
  AuthenticatedAdminVisualModeRouteImport.update({
    id: '/admin_/visual-mode',
    path: '/admin/visual-mode',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminVisualMapRoute =
  AuthenticatedAdminVisualMapRouteImport.update({
    id: '/admin_/visual-map',
    path: '/admin/visual-map',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminVideoMapRoute =
  AuthenticatedAdminVideoMapRouteImport.update({
    id: '/admin_/video-map',
    path: '/admin/video-map',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin_/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminTaxonomyRoute =
  AuthenticatedAdminTaxonomyRouteImport.update({
    id: '/admin_/taxonomy',
    path: '/admin/taxonomy',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSourcesRoute =
  AuthenticatedAdminSourcesRouteImport.update({
    id: '/admin_/sources',
    path: '/admin/sources',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSourcePacksRoute =
  AuthenticatedAdminSourcePacksRouteImport.update({
    id: '/admin_/source-packs',
    path: '/admin/source-packs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminScreenshotRightsRoute =
  AuthenticatedAdminScreenshotRightsRouteImport.update({
    id: '/admin_/screenshot-rights',
    path: '/admin/screenshot-rights',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminQuestionsRoute =
  AuthenticatedAdminQuestionsRouteImport.update({
    id: '/admin_/questions',
    path: '/admin/questions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminOrgLibraryRoute =
  AuthenticatedAdminOrgLibraryRouteImport.update({
    id: '/admin_/org-library',
    path: '/admin/org-library',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminFoundingAccessRoute =
  AuthenticatedAdminFoundingAccessRouteImport.update({
    id: '/admin_/founding-access',
    path: '/admin/founding-access',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminFeedbackRoute =
  AuthenticatedAdminFeedbackRouteImport.update({
    id: '/admin_/feedback',
    path: '/admin/feedback',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminFactoryRoute =
  AuthenticatedAdminFactoryRouteImport.update({
    id: '/admin_/factory',
    path: '/admin/factory',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCoverageRoute =
  AuthenticatedAdminCoverageRouteImport.update({
    id: '/admin_/coverage',
    path: '/admin/coverage',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminConversionsRoute =
  AuthenticatedAdminConversionsRouteImport.update({
    id: '/admin_/conversions',
    path: '/admin/conversions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSourcesIdRoute =
  AuthenticatedAdminSourcesIdRouteImport.update({
    id: '/admin_/sources_/$id',
    path: '/admin/sources/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSourcePacksIdRoute =
  AuthenticatedAdminSourcePacksIdRouteImport.update({
    id: '/admin_/source-packs_/$id',
    path: '/admin/source-packs/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminQuestionsIdRoute =
  AuthenticatedAdminQuestionsIdRouteImport.update({
    id: '/admin_/questions_/$id',
    path: '/admin/questions/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminConversionsIdRoute =
  AuthenticatedAdminConversionsIdRouteImport.update({
    id: '/admin_/conversions_/$id',
    path: '/admin/conversions/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ask': typeof AuthenticatedAskRoute
  '/checklists': typeof AuthenticatedChecklistsRoute
  '/learn': typeof AuthenticatedLearnRoute
  '/org-library': typeof AuthenticatedOrgLibraryRoute
  '/playbooks': typeof AuthenticatedPlaybooksRoute
  '/scenarios': typeof AuthenticatedScenariosRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/admin/conversions': typeof AuthenticatedAdminConversionsRoute
  '/admin/coverage': typeof AuthenticatedAdminCoverageRoute
  '/admin/factory': typeof AuthenticatedAdminFactoryRoute
  '/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/admin/founding-access': typeof AuthenticatedAdminFoundingAccessRoute
  '/admin/org-library': typeof AuthenticatedAdminOrgLibraryRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/admin/screenshot-rights': typeof AuthenticatedAdminScreenshotRightsRoute
  '/admin/source-packs': typeof AuthenticatedAdminSourcePacksRoute
  '/admin/sources': typeof AuthenticatedAdminSourcesRoute
  '/admin/taxonomy': typeof AuthenticatedAdminTaxonomyRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/video-map': typeof AuthenticatedAdminVideoMapRoute
  '/admin/visual-map': typeof AuthenticatedAdminVisualMapRoute
  '/admin/visual-mode': typeof AuthenticatedAdminVisualModeRoute
  '/admin/visual-needs': typeof AuthenticatedAdminVisualNeedsRoute
  '/admin/visual-review': typeof AuthenticatedAdminVisualReviewRoute
  '/lessons/$id': typeof AuthenticatedLessonsIdRoute
  '/playbooks/$id': typeof AuthenticatedPlaybooksIdRoute
  '/scenarios/$id': typeof AuthenticatedScenariosIdRoute
  '/admin/conversions/$id': typeof AuthenticatedAdminConversionsIdRoute
  '/admin/questions/$id': typeof AuthenticatedAdminQuestionsIdRoute
  '/admin/source-packs/$id': typeof AuthenticatedAdminSourcePacksIdRoute
  '/admin/sources/$id': typeof AuthenticatedAdminSourcesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ask': typeof AuthenticatedAskRoute
  '/checklists': typeof AuthenticatedChecklistsRoute
  '/learn': typeof AuthenticatedLearnRoute
  '/org-library': typeof AuthenticatedOrgLibraryRoute
  '/playbooks': typeof AuthenticatedPlaybooksRoute
  '/scenarios': typeof AuthenticatedScenariosRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/admin/conversions': typeof AuthenticatedAdminConversionsRoute
  '/admin/coverage': typeof AuthenticatedAdminCoverageRoute
  '/admin/factory': typeof AuthenticatedAdminFactoryRoute
  '/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/admin/founding-access': typeof AuthenticatedAdminFoundingAccessRoute
  '/admin/org-library': typeof AuthenticatedAdminOrgLibraryRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/admin/screenshot-rights': typeof AuthenticatedAdminScreenshotRightsRoute
  '/admin/source-packs': typeof AuthenticatedAdminSourcePacksRoute
  '/admin/sources': typeof AuthenticatedAdminSourcesRoute
  '/admin/taxonomy': typeof AuthenticatedAdminTaxonomyRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/video-map': typeof AuthenticatedAdminVideoMapRoute
  '/admin/visual-map': typeof AuthenticatedAdminVisualMapRoute
  '/admin/visual-mode': typeof AuthenticatedAdminVisualModeRoute
  '/admin/visual-needs': typeof AuthenticatedAdminVisualNeedsRoute
  '/admin/visual-review': typeof AuthenticatedAdminVisualReviewRoute
  '/lessons/$id': typeof AuthenticatedLessonsIdRoute
  '/playbooks/$id': typeof AuthenticatedPlaybooksIdRoute
  '/scenarios/$id': typeof AuthenticatedScenariosIdRoute
  '/admin/conversions/$id': typeof AuthenticatedAdminConversionsIdRoute
  '/admin/questions/$id': typeof AuthenticatedAdminQuestionsIdRoute
  '/admin/source-packs/$id': typeof AuthenticatedAdminSourcePacksIdRoute
  '/admin/sources/$id': typeof AuthenticatedAdminSourcesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ask': typeof AuthenticatedAskRoute
  '/_authenticated/checklists': typeof AuthenticatedChecklistsRoute
  '/_authenticated/learn': typeof AuthenticatedLearnRoute
  '/_authenticated/org-library': typeof AuthenticatedOrgLibraryRoute
  '/_authenticated/playbooks': typeof AuthenticatedPlaybooksRoute
  '/_authenticated/scenarios': typeof AuthenticatedScenariosRoute
  '/_authenticated/videos': typeof AuthenticatedVideosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/_authenticated/admin_/conversions': typeof AuthenticatedAdminConversionsRoute
  '/_authenticated/admin_/coverage': typeof AuthenticatedAdminCoverageRoute
  '/_authenticated/admin_/factory': typeof AuthenticatedAdminFactoryRoute
  '/_authenticated/admin_/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/_authenticated/admin_/founding-access': typeof AuthenticatedAdminFoundingAccessRoute
  '/_authenticated/admin_/org-library': typeof AuthenticatedAdminOrgLibraryRoute
  '/_authenticated/admin_/questions': typeof AuthenticatedAdminQuestionsRoute
  '/_authenticated/admin_/screenshot-rights': typeof AuthenticatedAdminScreenshotRightsRoute
  '/_authenticated/admin_/source-packs': typeof AuthenticatedAdminSourcePacksRoute
  '/_authenticated/admin_/sources': typeof AuthenticatedAdminSourcesRoute
  '/_authenticated/admin_/taxonomy': typeof AuthenticatedAdminTaxonomyRoute
  '/_authenticated/admin_/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin_/video-map': typeof AuthenticatedAdminVideoMapRoute
  '/_authenticated/admin_/visual-map': typeof AuthenticatedAdminVisualMapRoute
  '/_authenticated/admin_/visual-mode': typeof AuthenticatedAdminVisualModeRoute
  '/_authenticated/admin_/visual-needs': typeof AuthenticatedAdminVisualNeedsRoute
  '/_authenticated/admin_/visual-review': typeof AuthenticatedAdminVisualReviewRoute
  '/_authenticated/lessons_/$id': typeof AuthenticatedLessonsIdRoute
  '/_authenticated/playbooks_/$id': typeof AuthenticatedPlaybooksIdRoute
  '/_authenticated/scenarios_/$id': typeof AuthenticatedScenariosIdRoute
  '/_authenticated/admin_/conversions_/$id': typeof AuthenticatedAdminConversionsIdRoute
  '/_authenticated/admin_/questions_/$id': typeof AuthenticatedAdminQuestionsIdRoute
  '/_authenticated/admin_/source-packs_/$id': typeof AuthenticatedAdminSourcePacksIdRoute
  '/_authenticated/admin_/sources_/$id': typeof AuthenticatedAdminSourcesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/contact'
    | '/legal'
    | '/login'
    | '/payment-success'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/update-password'
    | '/account'
    | '/admin'
    | '/ask'
    | '/checklists'
    | '/learn'
    | '/org-library'
    | '/playbooks'
    | '/scenarios'
    | '/videos'
    | '/auth/callback'
    | '/checkout/return'
    | '/admin/conversions'
    | '/admin/coverage'
    | '/admin/factory'
    | '/admin/feedback'
    | '/admin/founding-access'
    | '/admin/org-library'
    | '/admin/questions'
    | '/admin/screenshot-rights'
    | '/admin/source-packs'
    | '/admin/sources'
    | '/admin/taxonomy'
    | '/admin/users'
    | '/admin/video-map'
    | '/admin/visual-map'
    | '/admin/visual-mode'
    | '/admin/visual-needs'
    | '/admin/visual-review'
    | '/lessons/$id'
    | '/playbooks/$id'
    | '/scenarios/$id'
    | '/admin/conversions/$id'
    | '/admin/questions/$id'
    | '/admin/source-packs/$id'
    | '/admin/sources/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/contact'
    | '/legal'
    | '/login'
    | '/payment-success'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/update-password'
    | '/account'
    | '/admin'
    | '/ask'
    | '/checklists'
    | '/learn'
    | '/org-library'
    | '/playbooks'
    | '/scenarios'
    | '/videos'
    | '/auth/callback'
    | '/checkout/return'
    | '/admin/conversions'
    | '/admin/coverage'
    | '/admin/factory'
    | '/admin/feedback'
    | '/admin/founding-access'
    | '/admin/org-library'
    | '/admin/questions'
    | '/admin/screenshot-rights'
    | '/admin/source-packs'
    | '/admin/sources'
    | '/admin/taxonomy'
    | '/admin/users'
    | '/admin/video-map'
    | '/admin/visual-map'
    | '/admin/visual-mode'
    | '/admin/visual-needs'
    | '/admin/visual-review'
    | '/lessons/$id'
    | '/playbooks/$id'
    | '/scenarios/$id'
    | '/admin/conversions/$id'
    | '/admin/questions/$id'
    | '/admin/source-packs/$id'
    | '/admin/sources/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/checkout'
    | '/contact'
    | '/legal'
    | '/login'
    | '/payment-success'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/update-password'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/ask'
    | '/_authenticated/checklists'
    | '/_authenticated/learn'
    | '/_authenticated/org-library'
    | '/_authenticated/playbooks'
    | '/_authenticated/scenarios'
    | '/_authenticated/videos'
    | '/auth/callback'
    | '/checkout/return'
    | '/_authenticated/admin_/conversions'
    | '/_authenticated/admin_/coverage'
    | '/_authenticated/admin_/factory'
    | '/_authenticated/admin_/feedback'
    | '/_authenticated/admin_/founding-access'
    | '/_authenticated/admin_/org-library'
    | '/_authenticated/admin_/questions'
    | '/_authenticated/admin_/screenshot-rights'
    | '/_authenticated/admin_/source-packs'
    | '/_authenticated/admin_/sources'
    | '/_authenticated/admin_/taxonomy'
    | '/_authenticated/admin_/users'
    | '/_authenticated/admin_/video-map'
    | '/_authenticated/admin_/visual-map'
    | '/_authenticated/admin_/visual-mode'
    | '/_authenticated/admin_/visual-needs'
    | '/_authenticated/admin_/visual-review'
    | '/_authenticated/lessons_/$id'
    | '/_authenticated/playbooks_/$id'
    | '/_authenticated/scenarios_/$id'
    | '/_authenticated/admin_/conversions_/$id'
    | '/_authenticated/admin_/questions_/$id'
    | '/_authenticated/admin_/source-packs_/$id'
    | '/_authenticated/admin_/sources_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ContactRoute: typeof ContactRoute
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/videos': {
      id: '/_authenticated/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof AuthenticatedVideosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scenarios': {
      id: '/_authenticated/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof AuthenticatedScenariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/playbooks': {
      id: '/_authenticated/playbooks'
      path: '/playbooks'
      fullPath: '/playbooks'
      preLoaderRoute: typeof AuthenticatedPlaybooksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/org-library': {
      id: '/_authenticated/org-library'
      path: '/org-library'
      fullPath: '/org-library'
      preLoaderRoute: typeof AuthenticatedOrgLibraryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learn': {
      id: '/_authenticated/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AuthenticatedLearnRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checklists': {
      id: '/_authenticated/checklists'
      path: '/checklists'
      fullPath: '/checklists'
      preLoaderRoute: typeof AuthenticatedChecklistsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ask': {
      id: '/_authenticated/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AuthenticatedAskRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scenarios_/$id': {
      id: '/_authenticated/scenarios_/$id'
      path: '/scenarios/$id'
      fullPath: '/scenarios/$id'
      preLoaderRoute: typeof AuthenticatedScenariosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/playbooks_/$id': {
      id: '/_authenticated/playbooks_/$id'
      path: '/playbooks/$id'
      fullPath: '/playbooks/$id'
      preLoaderRoute: typeof AuthenticatedPlaybooksIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lessons_/$id': {
      id: '/_authenticated/lessons_/$id'
      path: '/lessons/$id'
      fullPath: '/lessons/$id'
      preLoaderRoute: typeof AuthenticatedLessonsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin_/visual-review': {
      id: '/_authenticated/admin_/visual-review'
      path: '/admin/visual-review'
      fullPath: '/admin/visual-review'
      preLoaderRoute: typeof AuthenticatedAdminVisualReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin_/visual-needs': {
      id: '/_authenticated/admin_/visual-needs'
      path: '/admin/visual-needs'
      fullPath: '/admin/visual-needs'
      preLoaderRoute: typeof AuthenticatedAdminVisualNeedsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin_/visual-mode': {
      id: '/_authenticated/admin_/visual-mode'
      path: '/admin/visual-mode'
      fullPath: '/admin/visual-mode'
      preLoaderRoute: typeof AuthenticatedAdminVisualModeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin_/visual-map': {
      id: '/_authenticated/admin_/visual-map'
      path: '/admin/visual-map'
      fullPath: '/admin/visual-map'
      preLoaderRoute: typeof AuthenticatedAdminVisualMapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin_/video-map': {
      id: '/_authenticated/admin_/video-map'
      path: '/admin/video-map'
      fullPath: '/admin/video-map'
      preLoaderRoute: typeof AuthenticatedAdminVideoMapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin_/users': {
      id: '/_authenticated/admin_/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin_/taxonomy': {
      id: '/_authenticated/admin_/taxonomy'
      path: '/admin/taxonomy'
      fullPath: '/admin/taxonomy'
      preLoaderRoute: typeof AuthenticatedAdminTaxonomyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin_/sources': {
      id: '/_authenticated/admin_/sources'
      path: '/admin/sources'
      fullPath: '/admin/sources'
      preLoaderRoute: typeof AuthenticatedAdminSourcesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin_/source-packs': {
      id: '/_authenticated/admin_/source-packs'
      path: '/admin/source-packs'
      fullPath: '/admin/source-packs'
      preLoaderRoute: typeof AuthenticatedAdminSourcePacksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin_/screenshot-rights': {
      id: '/_authenticated/admin_/screenshot-rights'
      path: '/admin/screenshot-rights'
      fullPath: '/admin/screenshot-rights'
      preLoaderRoute: typeof AuthenticatedAdminScreenshotRightsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin_/questions': {
      id: '/_authenticated/admin_/questions'
      path: '/admin/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AuthenticatedAdminQuestionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin_/org-library': {
      id: '/_authenticated/admin_/org-library'
      path: '/admin/org-library'
      fullPath: '/admin/org-library'
      preLoaderRoute: typeof AuthenticatedAdminOrgLibraryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin_/founding-access': {
      id: '/_authenticated/admin_/founding-access'
      path: '/admin/founding-access'
      fullPath: '/admin/founding-access'
      preLoaderRoute: typeof AuthenticatedAdminFoundingAccessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin_/feedback': {
      id: '/_authenticated/admin_/feedback'
      path: '/admin/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AuthenticatedAdminFeedbackRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin_/factory': {
      id: '/_authenticated/admin_/factory'
      path: '/admin/factory'
      fullPath: '/admin/factory'
      preLoaderRoute: typeof AuthenticatedAdminFactoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin_/coverage': {
      id: '/_authenticated/admin_/coverage'
      path: '/admin/coverage'
      fullPath: '/admin/coverage'
      preLoaderRoute: typeof AuthenticatedAdminCoverageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin_/conversions': {
      id: '/_authenticated/admin_/conversions'
      path: '/admin/conversions'
      fullPath: '/admin/conversions'
      preLoaderRoute: typeof AuthenticatedAdminConversionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin_/sources_/$id': {
      id: '/_authenticated/admin_/sources_/$id'
      path: '/admin/sources/$id'
      fullPath: '/admin/sources/$id'
      preLoaderRoute: typeof AuthenticatedAdminSourcesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin_/source-packs_/$id': {
      id: '/_authenticated/admin_/source-packs_/$id'
      path: '/admin/source-packs/$id'
      fullPath: '/admin/source-packs/$id'
      preLoaderRoute: typeof AuthenticatedAdminSourcePacksIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin_/questions_/$id': {
      id: '/_authenticated/admin_/questions_/$id'
      path: '/admin/questions/$id'
      fullPath: '/admin/questions/$id'
      preLoaderRoute: typeof AuthenticatedAdminQuestionsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin_/conversions_/$id': {
      id: '/_authenticated/admin_/conversions_/$id'
      path: '/admin/conversions/$id'
      fullPath: '/admin/conversions/$id'
      preLoaderRoute: typeof AuthenticatedAdminConversionsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAskRoute: typeof AuthenticatedAskRoute
  AuthenticatedChecklistsRoute: typeof AuthenticatedChecklistsRoute
  AuthenticatedLearnRoute: typeof AuthenticatedLearnRoute
  AuthenticatedOrgLibraryRoute: typeof AuthenticatedOrgLibraryRoute
  AuthenticatedPlaybooksRoute: typeof AuthenticatedPlaybooksRoute
  AuthenticatedScenariosRoute: typeof AuthenticatedScenariosRoute
  AuthenticatedVideosRoute: typeof AuthenticatedVideosRoute
  AuthenticatedAdminConversionsRoute: typeof AuthenticatedAdminConversionsRoute
  AuthenticatedAdminCoverageRoute: typeof AuthenticatedAdminCoverageRoute
  AuthenticatedAdminFactoryRoute: typeof AuthenticatedAdminFactoryRoute
  AuthenticatedAdminFeedbackRoute: typeof AuthenticatedAdminFeedbackRoute
  AuthenticatedAdminFoundingAccessRoute: typeof AuthenticatedAdminFoundingAccessRoute
  AuthenticatedAdminOrgLibraryRoute: typeof AuthenticatedAdminOrgLibraryRoute
  AuthenticatedAdminQuestionsRoute: typeof AuthenticatedAdminQuestionsRoute
  AuthenticatedAdminScreenshotRightsRoute: typeof AuthenticatedAdminScreenshotRightsRoute
  AuthenticatedAdminSourcePacksRoute: typeof AuthenticatedAdminSourcePacksRoute
  AuthenticatedAdminSourcesRoute: typeof AuthenticatedAdminSourcesRoute
  AuthenticatedAdminTaxonomyRoute: typeof AuthenticatedAdminTaxonomyRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminVideoMapRoute: typeof AuthenticatedAdminVideoMapRoute
  AuthenticatedAdminVisualMapRoute: typeof AuthenticatedAdminVisualMapRoute
  AuthenticatedAdminVisualModeRoute: typeof AuthenticatedAdminVisualModeRoute
  AuthenticatedAdminVisualNeedsRoute: typeof AuthenticatedAdminVisualNeedsRoute
  AuthenticatedAdminVisualReviewRoute: typeof AuthenticatedAdminVisualReviewRoute
  AuthenticatedLessonsIdRoute: typeof AuthenticatedLessonsIdRoute
  AuthenticatedPlaybooksIdRoute: typeof AuthenticatedPlaybooksIdRoute
  AuthenticatedScenariosIdRoute: typeof AuthenticatedScenariosIdRoute
  AuthenticatedAdminConversionsIdRoute: typeof AuthenticatedAdminConversionsIdRoute
  AuthenticatedAdminQuestionsIdRoute: typeof AuthenticatedAdminQuestionsIdRoute
  AuthenticatedAdminSourcePacksIdRoute: typeof AuthenticatedAdminSourcePacksIdRoute
  AuthenticatedAdminSourcesIdRoute: typeof AuthenticatedAdminSourcesIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAskRoute: AuthenticatedAskRoute,
  AuthenticatedChecklistsRoute: AuthenticatedChecklistsRoute,
  AuthenticatedLearnRoute: AuthenticatedLearnRoute,
  AuthenticatedOrgLibraryRoute: AuthenticatedOrgLibraryRoute,
  AuthenticatedPlaybooksRoute: AuthenticatedPlaybooksRoute,
  AuthenticatedScenariosRoute: AuthenticatedScenariosRoute,
  AuthenticatedVideosRoute: AuthenticatedVideosRoute,
  AuthenticatedAdminConversionsRoute: AuthenticatedAdminConversionsRoute,
  AuthenticatedAdminCoverageRoute: AuthenticatedAdminCoverageRoute,
  AuthenticatedAdminFactoryRoute: AuthenticatedAdminFactoryRoute,
  AuthenticatedAdminFeedbackRoute: AuthenticatedAdminFeedbackRoute,
  AuthenticatedAdminFoundingAccessRoute: AuthenticatedAdminFoundingAccessRoute,
  AuthenticatedAdminOrgLibraryRoute: AuthenticatedAdminOrgLibraryRoute,
  AuthenticatedAdminQuestionsRoute: AuthenticatedAdminQuestionsRoute,
  AuthenticatedAdminScreenshotRightsRoute:
    AuthenticatedAdminScreenshotRightsRoute,
  AuthenticatedAdminSourcePacksRoute: AuthenticatedAdminSourcePacksRoute,
  AuthenticatedAdminSourcesRoute: AuthenticatedAdminSourcesRoute,
  AuthenticatedAdminTaxonomyRoute: AuthenticatedAdminTaxonomyRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminVideoMapRoute: AuthenticatedAdminVideoMapRoute,
  AuthenticatedAdminVisualMapRoute: AuthenticatedAdminVisualMapRoute,
  AuthenticatedAdminVisualModeRoute: AuthenticatedAdminVisualModeRoute,
  AuthenticatedAdminVisualNeedsRoute: AuthenticatedAdminVisualNeedsRoute,
  AuthenticatedAdminVisualReviewRoute: AuthenticatedAdminVisualReviewRoute,
  AuthenticatedLessonsIdRoute: AuthenticatedLessonsIdRoute,
  AuthenticatedPlaybooksIdRoute: AuthenticatedPlaybooksIdRoute,
  AuthenticatedScenariosIdRoute: AuthenticatedScenariosIdRoute,
  AuthenticatedAdminConversionsIdRoute: AuthenticatedAdminConversionsIdRoute,
  AuthenticatedAdminQuestionsIdRoute: AuthenticatedAdminQuestionsIdRoute,
  AuthenticatedAdminSourcePacksIdRoute: AuthenticatedAdminSourcePacksIdRoute,
  AuthenticatedAdminSourcesIdRoute: AuthenticatedAdminSourcesIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface CheckoutRouteChildren {
  CheckoutReturnRoute: typeof CheckoutReturnRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutReturnRoute: CheckoutReturnRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CheckoutRoute: CheckoutRouteWithChildren,
  ContactRoute: ContactRoute,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
